kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name:  edgex-init-vault-pvc
 namespace: vault
 annotations:
    volume.beta.kubernetes.io/storage-class: "openebs-rwx"
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: "openebs-rwx"
  resources:
    requests:
      storage: 1Gi
