apiVersion: v1
kind: Service
metadata:
  name: {{ include "kong-edge-vault.fullname" . }}
  labels:
    {{- include "kong-edge-vault.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    {{- include "kong-edge-vault.selectorLabels" . | nindent 4 }}
