# Default values for kong-edge-vault.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hashicorp/vault:latest
  pullPolicy: Always
  name: edgex-vault
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
   capabilities:
     add:
      - IPC_LOCK
   runAsUser: 100
   runAsGroup: 1000
   fsGroup: 1000

service:
  type: ClusterIP
  port: 8200
  targetPort: 8200


ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: vault
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: kong-edgex-vault
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


nodeSelector: {}

tolerations: []

affinity: {}


volumes:
  - name: edgex-init
    persistentVolumeClaim:
      claimName: edgex-init-vault-pvc
      readOnly: false
  - name: vault-file
    persistentVolumeClaim:
      claimName: vault-file-pvc
  - name: vault-logs
    persistentVolumeClaim:
      claimName: vault-logs-pvc
  - emptyDir:
      medium: Memory
    name: vault-config-tmp

volumeMounts:
  - mountPath: /mnt
    name: edgex-init
    readOnly: false
  - mountPath: /vault/file
    name: vault-file
  - mountPath: /vault/logs
    name: vault-logs
  - mountPath: /vault/config
    name: vault-config-tmp

hostname: edgex-vault
restartPolicy: Always

env:
  PROXY_SETUP_HOST: edgex-security-proxy-setup
  STAGEGATE_BOOTSTRAPPER_HOST: gorilla-kong-edge-security-bootstrapper.bootstrapper.svc.cluster.local
  STAGEGATE_BOOTSTRAPPER_STARTPORT: "54321"
  STAGEGATE_DATABASE_HOST: gorilla-kong-edge-redis-database.redis.svc.cluster.local
  STAGEGATE_DATABASE_PORT: "6379"
  STAGEGATE_DATABASE_READYPORT: "6379"
  STAGEGATE_READY_TORUNPORT: "54329"
  STAGEGATE_REGISTRY_HOST: gorilla-kong-edge-redis-database.consul.svc.cluster.local
  STAGEGATE_REGISTRY_PORT: "8500"
  STAGEGATE_REGISTRY_READYPORT: "54324"
  STAGEGATE_SECRETSTORESETUP_HOST: gorilla-kong-edge-security-secret-store-setup.security-store.svc.cluster.local
  STAGEGATE_SECRETSTORESETUP_TOKENS_READYPORT: "54322"
  STAGEGATE_WAITFOR_TIMEOUT: 60s
  VAULT_ADDR: http://gorilla-kong-edge-vault:8200
  VAULT_CONFIG_DIR: /vault/config
  VAULT_UI: "true"

args:
  - server

command:
  - /edgex-init/vault_wait_install.sh

dependencies:
  app:
    bootstrapper: kong-edge-bootstrapper
